### ISSUE TITLE
Cannot resolve *.es filenames in Node.js projects when using Babel

### ISSUE THREAD

**Issue by BohdanTkachenko** [BohdanTkachenko/eslint-plugin-require-path-exists#3]

**Comment by mjackson** [comment]
Not sure if this is related, but it would also be nice to support files with a `.jsx` extension.

**Comment by BohdanTkachenko** [comment]
@mjackson, yes, they are related, thanks.

If you're using it with Webpack in your project, then as a temporary solution you can just specify all extensions that you need in webpack.config.js and it should work with Node.js files too.

Currently thinking about how to correctly detect extensions supported by Node.js. In the case with Webpack, we're just parsing webpack.config.js to get supported extensions from there, but a correct way to do it in Node.js is to parse it in real-time.

**Comment by BohdanTkachenko** [comment]
Fixed with https://github.com/BohdanTkachenko/eslint-plugin-require-path-exists/pull/11 - now you should pass config to this plugin if you need any specific file extensions. Please see README.md for the details
