### ISSUE TITLE
Rules (as documented) not found by ESLint

### ISSUE THREAD

**Issue by dominicbarnes** [BohdanTkachenko/eslint-plugin-require-path-exists#6]
In this lib's readme, the rules are referred to as:
- require-path-exists/exists
- require-path-exists/not_empty
- require-path-exists/too_many_arguments

However, with ESLint it doesn't seem to find these rules:

> Definition for rule 'require-path-exists/not_empty' was not found

If I switch to camel-case, (ie: `require-path-exists/notEmpty`) it works as expected. I'm not sure if this is just outdated documentation, or if ESLint used to translate camel-case into snake-case or what.

**Comment by BohdanTkachenko** [comment]
Thanks, @dominicbarnes, it was a documentation issue.
