### ISSUE TITLE
Doesn't work with complex webpack aliases

### ISSUE THREAD

**Issue by chollier** [BohdanTkachenko/eslint-plugin-require-path-exists#8]
In https://webpack.github.io/docs/configuration.html#resolve-alias it says we can do 
alias: `{ xyz: "/some/dir" }`
usage: `require("xyz/file.js")` should yield `/some/dir/file.js`

I have in my webpack config :

``` javascript
    alias: {
      "selectors": path.join(__dirname, "src/js/selectors")
    }
```

and in my code :

``` javascript
import { getMetadata, getLoading } from "selectors/paginationSelector";
```

but I do get : 

```
src/js/components/jobs/detail/tabs/JobStoresTab.js|7 col 2 error| Cannot find module 'selectors/paginationSelector' (require-path-exists/exists)
```

**Comment by BohdanTkachenko** [comment]
Should work now. Feel free to reopen this issue if problem still reproduces.

**Comment by chollier** [comment]
that did it, thanks !!
